#!/usr/bin/env python3
from os import environ

environ['PYGAME_HIDE_SUPPORT_PROMPT'] = '1'

from argparse import ArgumentParser, FileType
from xml.etree import ElementTree

from pygame.math import Vector2
from svg.path import parse_path


def complex_to_tuple(c):
    return c.real, c.imag


def get_coordinates(path):
    for e in path:
        start = Vector2(complex_to_tuple(e.start))
        yield start
    yield Vector2(complex_to_tuple(path[-1].end))


def main(svg, resolution):
    print('# Path: coding-challenge-racer/extract_svg_path')
    print('import os.path')
    print()
    print('import pygame')
    print()
    print(f"name = '{svg.name}'")
    print(f'resolution = {resolution}')
    print("background = pygame.image.load(os.path.splitext(__file__)[0] + '.jpg')")
    print('lines = [')
    tree = ElementTree.parse(svg)
    root = tree.getroot()
    height = float(root.attrib['height'])
    for child in root:
        if child.tag == '{http://www.w3.org/2000/svg}path':
            d = child.attrib['d']
            path = parse_path(d)
            for c in get_coordinates(path):
                c.y = height - c.y
                c *= resolution
                decimals = 13
                c.x = round(c.x, decimals)
                c.y = round(c.y, decimals)
                print(f'  {tuple(c)},')
    print(']')


if __name__ == '__main__':
    parser = ArgumentParser()
    parser.add_argument('svg', type=FileType())
    parser.add_argument('--resolution', type=float, default=0.1, help='Resolution of the path [m/pixel]')
    args = parser.parse_args()
    main(**vars(args))
